### ISSUE TITLE
Lint fails with bootstrap

### ISSUE THREAD

**Issue by JohnRodney** [poetic/stanza#13]
Expected: The project on --create should generate a project that passes all linting.

Observed: 
```
/Users/john/projects/meteor/fpnreboot/client/main.jsx
  2:24  error  Unable to resolve path to module 'meteor/meteor'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

This can be prevented by adding to the `.eslintrc` file:

```
{
  "extends": "airbnb",
  "rules": {
    "import/no-unresolved": [
      2, { "ignore": ["^meteor/"] }
    ]
  }
}
```

This is suggested in the Meteor 1.3 guide http://guide.meteor.com/code-style.html#eslint-installing

**Comment by Chun-Yang** [comment]
Can we follow http://guide.meteor.com/code-style.html#eslint-installing all the way and install the linter they recommend?
