### ISSUE TITLE
_meteor.Meteor.loggingIn is not a function

### ISSUE THREAD

**Issue by dvmorris** [poetic/stanza#26]
On a newly generated stanza project, I received the following error:

`_meteor.Meteor.loggingIn is not a function`

I noticed that the function loggingIn() is defined in accounts-base [here](https://github.com/meteor/meteor/blob/be986fd70926c9dd8eff6d8866205f236c8562c4/packages/accounts-base/accounts_client.js), and adding this to `.meteor/packages` seemed to resolve the issue:

```
accounts-base               # A user account system
accounts-password           # Password support for accounts
```

**Comment by Chun-Yang** [comment]
fixed, added accounts-base
