### ISSUE TITLE
npm WARN react-redux@4.4.5 requires a peer of redux@^2.0.0 || ^3.0.0 but none was installed.

### ISSUE THREAD

**Issue by dvmorris** [poetic/stanza#33]
## Steps to reproduce (using this [design.zip](https://github.com/poetic/stanza/files/312376/design.zip) file):
```
meteor create stanza-test
cd stanza-test
stanza -c
cp ~/Downloads/design.zip ./
stanza -u
npm install
...
...
└── UNMET PEER DEPENDENCY redux@^2.0.0 || ^3.0.0

npm WARN react-redux@4.4.5 requires a peer of redux@^2.0.0 || ^3.0.0 but none was installed.
```

## Environment:
```
$ node --version
v6.2.1
$ npm --version
3.9.5
$ meteor --version
Meteor 1.3.2.4
$ npm ls --global=true --depth=0
/usr/local/lib
├── chimp@0.35.0
├── mantra-cli@0.3.12
├── npm@3.9.5
├── poetic-stanza@0.4.1
├── webpack@1.13.1
└── webpack-dev-server@1.14.1
```

**Comment by dvmorris** [comment]
My solution was to manually add this to the stanza-generated package.json file, but it seems like this should be automatically included. This was working fine last week.

```
    "react-super-components": "^0.3.5",
    "redux": "^3.5.2",  <-- had to manually add this line to package.json
    "redux-thunk": "^2.1.0"
```

**Comment by pferdone** [comment]
@dvmorris i followed your advice and manually installed redux
`npm i --save redux`

**Comment by Chun-Yang** [comment]
Done.

**Comment by mtrabelsi** [comment]
I ran into this too, and I just wonder why does this breaks? Normally should be automatically intalled..

**Comment by malidharam** [comment]
@dvmorris : Solved issue to me.

**Comment by PocketNinjaDesign** [comment]
Yeah it's a weird one, that you have to have redux installed before installing react-redux.  Just went through the same issue myself just now.

Could do with seeing on npm react-redux to make sure redux is installed first.  Would be the best place to add it on this page

https://www.npmjs.com/package/react-redux

Then nobody will have any problems.
