### ISSUE TITLE
Stanza does not add npm packages to package.json that were included via data-component-imports statements

### ISSUE THREAD

**Issue by dvmorris** [poetic/stanza#35]
If you include a `data-component-imports` attribute on a component in WebFlow as described in the reacterminator docs [here](https://github.com/poetic/reacterminator#data-attributes), stanza includes the import statements at the top of the component file, but it does not add the corresponding npm packages to package.json. 

Perhaps it is too complex for stanza to be responsible for this in addition to everything else it is doing, but it would be helpful for the script to at least output to the console a message that says something like, 

```
Some of the generated components are importing custom npm packages. Be sure to add the correct versions of these packages to package.json:
- moment
- ...
- etc.
```

**Comment by dvmorris** [comment]
I apologize for putting this in the wrong repository. This is really a reacterminator issue.

**Comment by Chun-Yang** [comment]
Port it to https://github.com/poetic/reacterminator/issues/15
