### ISSUE TITLE
Generated App.jsx Stack component '*' problem

### ISSUE THREAD

**Issue by inestyne** [poetic/stanza#53]
I think there's a mis-config in the app created by 'stanza c' maybe? I'm very new to node but i'm guessing this is just a configuration problem in the main app and not the generated files.

Ran:
  stanza c velocity
  cd velocity
  cp ../design.zip .
  stanza update

Generated App.jsx looks like:

```
class App extends React.Component {
  render() {
    return (
        <Provider store={store}>
          <Stack indexKey='path' activeLayerIndex={this.props.path}>
            <Contact index='contact' />
            <Index index='' />
          </Stack>
        </Provider>
    );
  }
}
```

I had to add an '*' to index to get the site to function:

```
class App extends React.Component {
  render() {
    return (
        <Provider store={store}>
          <Stack indexKey='path' activeLayerIndex={this.props.path}>
            <Contact index='contact' />
            <Index index='*' />
          </Stack>
        </Provider>
    );
  }
}
```

This would have to be done every time I ran stanza update. Which would suck... :)

**Comment by Chun-Yang** [comment]
Hey @inestyne , the boilerplate generated by stanza have authentication wall built in. If you go to `client/imports/custom/components/App.jsx` You will find the code that block the app from rendering a specific route.

Basically, you can make any route 'public' by adding the route name to `PUBLIC_ROUTES` at line 34.

**Comment by inestyne** [comment]
This worked thanks
